config/routes.rb
Omrails::Application.routes.draw do

  devise_for :views

devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

get 'about' => 'pages#about'
get 'courses' => 'pages#courses'

root :to => 'pages#home'

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :as => [:default, :admin]
  validates_presence_of :name
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
	def action
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "VCDrive", "http://onemonthrails.com" %>
		by <%= link_to "Nils White", "http://mattangriffel.com" %>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content. The next code sets up the button using btn (style btn-navbar) and each of the "icon-bar" lines create lines on the button itself. -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <!-- leaving the brand out here so it's shown all the time even when the page goes small-->
     
      <%= link_to "VCDrive", root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
    	  	<li><%= link_to "Home", root_path %></li>
  	      <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Courses", courses_path %></li>
    	  </ul>
    	  <ul class="nav pull-right">
          <!-- Could add in a search bar -->
          <% if user_signed_in? %>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <!-- Could add in an inline login field so users can login from any page (in header) -->
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
    		  
    	  </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  	  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>

	</head>
	<body>

		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<div class="hero-unit">
	<h1>About VCDrive</h1>
	<p>
		<%= link_to "VCDrive", "http://onemonthrails.com" %>
		is a company that provides you the tools you need to take the next step.
	</p>
	<p>
		Follow us to the edge. Are you ready to take the  
		<%= link_to "leap", "http://rubyonrails.org" %>
		...?
	</p>
</div>

app/views/pages/courses.html.erb
<div class="hero-unit">
	<h1>Courses</h1>
	<p>
		<%= link_to "VCDrive Courses", "http://onemonthrails.com" %>
		are the resources you need to make the next step toward
		<%= link_to "success", "http://rubyonrails.org" %>
		. This is where your journey begins!
	</p>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>

	<div class="hero-unit">
		<h1><font color="green">VC</font>Drive</h1>
		<h2>- Members Page -</h2>
		<p>
			Now you've taken the first step and you're on the road to your dream. Keep walking...
		<p/>
		<p>
			<%= link_to "Start Now", new_user_registration_path, class: "btn btn-success btn-large"%>
		<p/>
	</div>
	<div class="hero-unit">
		<h3>The First Hole</h3>
		<p>
			You've got an idea, it's a good one. 437 yards and you're aiming right at that pin. What is going through your mind? I wonder how you're going to handle the headwind? Should you club up? Can you even make this shot? You've never played this course before, you've never seen this hole before, but you know you can hit this shot from years of experience. So what are you going to do...? 
		</p>
		<p>
		</p>
		<p>
			Now is the time. You have to trust your training and trust your swing and aim visualize the shot...
		</p>
		<p>
			You can't do any of this if you're missing a few key pieces:
		</p>
		<p>
			1) The training: have you really done this before? Do you know how to handle the environment? the conditions? the pressure? the odds?
		</p>
		<p>
			2) The right clubs: have you got the ride hardware? the right resources? the right swing?
		</p>
		<p>
			3) The drive: do you really have what it takes to compete at this level? How are you going to cross the chasm and play with the big boys? You've seen it done on TV, but how are you, YOU, going to do it?
		<p/>
		<p>
			<%= link_to "Hole Two", root_path, class: "btn btn-info"%>
		<p/>
	</div>

<% else %>
	
	<div class="hero-unit">
		<h1>Welcome to VCDrive</h1>
		<p>
			You've got the idea, we've got the strategy. Take our advice, you 
			<strong>are</strong> 
			ready! Join the new market and create something
			<%= link_to "inspiring", "http://onemonthrails.com" %>
			...
		<p/>
		<p>
			<%= link_to "Start Now", new_user_registration_path, class: "btn btn-success btn-large"%>
		<p/>
	</div>

<% end %>